### ISSUE TITLE
Can't run script from another folder

### ISSUE THREAD

**Issue by 3dsf** [intel-isl/MiDaS#40]
**when running Midas from another folder:**
```
python ../MiDaS/run.py 
initialize
device: cuda
Loading weights:  model-f46da743.pt
Using cache found in /home/3dsf/.cache/torch/hub/facebookresearch_WSL-Images_master
Traceback (most recent call last):
  File "../MiDaS/run.py", line 105, in <module>
    run(INPUT_PATH, OUTPUT_PATH, MODEL_PATH)
  File "../MiDaS/run.py", line 29, in run
    model = MidasNet(model_path, non_negative=True)
  File "/home/3dsf/MiDaS/midas/midas_net.py", line 47, in __init__
    self.load(path)
  File "/home/3dsf/MiDaS/midas/base_model.py", line 11, in load
    parameters = torch.load(path)
  File "/home/3dsf/MiDaS/envs/lib/python3.7/site-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'model-f46da743.pt'
```
**This could be a feature, I guess.**  Anyways, great job, I've tested it several times and here is a [https://www.reddit.com/r/MagicEye/comments/iabxms/im_not_sorry_not_even_a_little/](magicEye Video made using MiDas)

**Comment by ranftlr** [comment]
We assume that the model weights are in the same folder as the script. Would consider this neither a bug, nor a feature. 

Thanks for showing us what you are doing with MiDaS. Very creative application :)

**Comment by kjyothiswaroop** [comment]
> **when running Midas from another folder:**
> 
> ```
> python ../MiDaS/run.py 
> initialize
> device: cuda
> Loading weights:  model-f46da743.pt
> Using cache found in /home/3dsf/.cache/torch/hub/facebookresearch_WSL-Images_master
> Traceback (most recent call last):
>   File "../MiDaS/run.py", line 105, in <module>
>     run(INPUT_PATH, OUTPUT_PATH, MODEL_PATH)
>   File "../MiDaS/run.py", line 29, in run
>     model = MidasNet(model_path, non_negative=True)
>   File "/home/3dsf/MiDaS/midas/midas_net.py", line 47, in __init__
>     self.load(path)
>   File "/home/3dsf/MiDaS/midas/base_model.py", line 11, in load
>     parameters = torch.load(path)
>   File "/home/3dsf/MiDaS/envs/lib/python3.7/site-packages/torch/serialization.py", line 381, in load
>     f = open(f, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'model-f46da743.pt'
> ```
> 
> **This could be a feature, I guess.** Anyways, great job, I've tested it several times and here is a [magicEye Video made using MiDas](https://www.reddit.com/r/MagicEye/comments/iabxms/im_not_sorry_not_even_a_little/)

How Did you fix the error I am getting the same error could you help me out?

**Comment by 3dsf** [comment]
I think I did something like this

`scriptDir = os.path.realpath(__directory__)  `

```
if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('-i', '--input_path', 
        default=os.path.join(scriptDir,'input'),
        help='folder with input images'
    )
```
_you'd have to do it for all the defaults_
