### ISSUE TITLE
Got unexpected keyword argument "groups"

### ISSUE THREAD

**Issue by zendevil** [intel-isl/MiDaS#46]
python3 run.py
initialize
device: cuda
Loading weights:  model-f46da743.pt
Downloading: "https://github.com/facebookresearch/WSL-Images/archive/master.zip" to /home/prikshet/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "run.py", line 105, in <module>
    run(INPUT_PATH, OUTPUT_PATH, MODEL_PATH)
  File "run.py", line 29, in run
    model = MidasNet(model_path, non_negative=True)
  File "/home/prikshet/midas/midas/midas_net.py", line 30, in __init__
    self.pretrained, self.scratch = _make_encoder(features, use_pretrained)
  File "/home/prikshet/midas/midas/blocks.py", line 6, in _make_encoder
    pretrained = _make_pretrained_resnext101_wsl(use_pretrained)
  File "/home/prikshet/midas/midas/blocks.py", line 26, in _make_pretrained_resnext101_wsl
    resnet = torch.hub.load("facebookresearch/WSL-Images", "resnext101_32x8d_wsl")
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 354, in load
    model = entry(*args, **kwargs)
  File "/home/prikshet/.cache/torch/hub/facebookresearch_WSL-Images_master/hubconf.py", line 39, in resnext101_32x8d_wsl
    return _resnext('resnext101_32x8d', Bottleneck, [3, 4, 23, 3], True, progress, **kwargs)
  File "/home/prikshet/.cache/torch/hub/facebookresearch_WSL-Images_master/hubconf.py", line 23, in _resnext
    model = ResNet(block, layers, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'groups'

**Comment by ranftlr** [comment]
You might be using an incompatible version of PyTorch and/or Torchvision. What versions are you using? You can check with:

```python
import torch
import torchvision

print(torch.__version__)
print(torchvision.__version__)
```
I tested it just now and I don't see the error with PyTorch 1.6.0 and Torchvision 0.7.0.

**Comment by ranftlr** [comment]
Closing due to inactivity.

**Comment by 3dsf** [comment]
just a confirmation, it is related to the torchvision version
_conda had installed something below 0.3.0 for me_

---  

> TypeError: __init__() got an unexpected keyword argument 'groups'

torchvision version was too low (need 0.3.0 or higher) as per 
https://github.com/facebookresearch/WSL-Images/issues/3  

---

if using a **conda** virtual environment, I'd recommend upgrading via pip 
`pip3 install torchvision --upgrade`

**Comment by AlexanderStohr** [comment]
running on Windows

initial state:
torch=1.7.1+cpu
torchvision=0.2.2

this line failed for me - no newer version found:
pip3 install torchvision --upgrade

then i tried this one:
pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
(found it there: https://stackoverflow.com/questions/62513412/cannot-install-pip-install-torchvision )

due to some access restriction i finally added "--user" on above

final result:
torch=1.5.1+cpu
torchvision=0.6.1+cpu

and previous dangling operation is now past.


alternate combinations of CPU/CUDA, OS, installer and alikes can be found via the tool here:
https://pytorch.org/get-started/locally/

for more version pairings and indication what might match with your python version:
https://pypi.org/project/torchvision/
