### ISSUE TITLE
Pytorch Errors

### ISSUE THREAD

**Issue by GregoryBetsey** [intel-isl/MiDaS#56]
I got this error after running MiDaS 2.1 

initialize
device: cpu
Loading weights:  model-f6b98070.pt
Using cache found in C:\Users\gregb/.cache\torch\hub\facebookresearch_WSL-Images_master
Traceback (most recent call last):
  File "run.py", line 151, in <module>
    run(args.input_path, args.output_path, args.model_weights, args.model_type, args.optimize)
  File "run.py", line 32, in run
    model = MidasNet(model_path, non_negative=True)
  File "C:\Users\gregb\Documents\Python\MiDaS\midas\midas_net.py", line 47, in __init__
    self.load(path)
  File "C:\Users\gregb\Documents\Python\MiDaS\midas\base_model.py", line 11, in load
    parameters = torch.load(path, map_location=torch.device('cpu'))
  File "C:\Users\gregb\anaconda3\envs\3DP\lib\site-packages\torch\serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "C:\Users\gregb\anaconda3\envs\3DP\lib\site-packages\torch\serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ..\caffe2\serialize\inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ..\caffe2\serialize\inline_container.cc:132)
(no backtrace available)

**Comment by ranftlr** [comment]
Seems like a version conflict. What is your PyTorch version?

**Comment by GregoryBetsey** [comment]
I updated to the latest version and it's working now. Thanks.
